openapi: 3.0.3
info:
  title: Space CMS API Service
  description: Auth service for SpaceCMS. An open source content management system.
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /api/v1/openapi.json:
    get:
      tags:
      - cms
      summary: Download ./gen/http/openapi.json
      operationId: cms#/api/v1/openapi.json
      responses:
        "200":
          description: File downloaded
  /api/v1/pages:
    post:
      tags:
      - cms
      summary: CreatePage cms
      description: Create an account by email address and password.
      operationId: cms#CreatePage
      parameters:
      - name: __Host-token
        in: cookie
        allowEmptyValue: true
        schema:
          type: string
          example: Deleniti voluptatibus quam repellat tenetur explicabo velit.
        example: Aut modi commodi rerum.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrantTokenRequestBody'
            example:
              email: Commodi architecto velit dolorem distinctio.
              password: Laborum quam.
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token2'
              example:
                accessExpiryTime: 1087056026976835113
                accessExpiryTimeStamp: Illum ut repellendus velit qui.
                accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
                refreshExpiryTime: 1220539258699969072
                refreshExpiryTimeStamp: Vero qui voluptatibus illum natus dignissimos.
                refreshToken: Commodi fugit et voluptas.
                token: Autem rerum.
        "400":
          description: 'badrequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 'notfound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 'servererror: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/user/signup:
    post:
      tags:
      - auth
      summary: CreateAccount auth
      description: Create an account by email address and password.
      operationId: auth#CreateAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequestBody'
            example:
              email: Itaque excepturi repellendus rerum tempore velit.
              id: Autem tenetur et voluptate possimus asperiores ea.
              name: Consectetur et saepe voluptas ex sit.
              password: Dolores eveniet molestias laudantium sequi hic perspiciatis.
      responses:
        "201":
          description: Created response.
        "400":
          description: 'badrequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 'notfound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 'servererror: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/user/tokens:
    post:
      tags:
      - auth
      summary: GrantToken auth
      description: Create an account by email address and password.
      operationId: auth#GrantToken
      parameters:
      - name: __Host-token
        in: cookie
        allowEmptyValue: true
        schema:
          type: string
          example: Illo nihil repellat voluptatem eos quidem.
        example: Et dolorem quos iure qui laudantium.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrantTokenRequestBody'
            example:
              email: Perspiciatis quibusdam dolor numquam.
              password: Odit vel esse voluptas.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
              example:
                accessExpiryTime: 3564172555033265585
                accessExpiryTimeStamp: Est optio consequatur sit sit doloremque.
                accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
                refreshExpiryTime: 73466722768413525
                refreshExpiryTimeStamp: Ad qui est quibusdam eaque et.
                refreshToken: Inventore ad inventore at omnis non commodi.
        "400":
          description: 'badrequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 'notfound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 'servererror: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CreateAccountRequestBody:
      type: object
      properties:
        email:
          type: string
          description: Email address of the user
          example: Voluptatum vitae provident quia.
        id:
          type: string
          description: ID of the user
          example: Quia dicta placeat et non.
        name:
          type: string
          description: Full name of the user
          example: Voluptatem aut et ipsum.
        password:
          type: string
          description: Password of the user. This is never returned to the client.
          example: Quia amet.
      example:
        email: Aliquam numquam voluptatem ad veritatis qui.
        id: Necessitatibus quia accusantium excepturi sit.
        name: Eum modi qui soluta omnis totam.
        password: Atque sint ea laborum.
      required:
      - email
      - name
      - password
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GrantTokenRequestBody:
      type: object
      properties:
        email:
          type: string
          description: User email
          example: Fugit vitae totam aut dignissimos.
        password:
          type: string
          description: User password
          example: Eum est corrupti non.
      example:
        email: Modi dolorem quaerat voluptas.
        password: Voluptatibus quia tenetur enim ad.
      required:
      - email
      - password
    Token:
      type: object
      properties:
        accessExpiryTime:
          type: integer
          example: 3599252296412658996
          format: int64
        accessExpiryTimeStamp:
          type: string
          example: Quod natus voluptatem.
        accessToken:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
        refreshExpiryTime:
          type: integer
          example: 6128336371357092582
          format: int64
        refreshExpiryTimeStamp:
          type: string
          example: Aut quo odio vel quisquam aut explicabo.
        refreshToken:
          type: string
          example: Aliquam aut omnis sint eveniet.
      example:
        accessExpiryTime: 7992353371575155920
        accessExpiryTimeStamp: Dolores sit sapiente quam minima porro corporis.
        accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
        refreshExpiryTime: 85603938504448694
        refreshExpiryTimeStamp: Reprehenderit et quod minima id accusantium perferendis.
        refreshToken: Consectetur sed et pariatur modi.
      required:
      - accessToken
      - refreshToken
      - accessExpiryTime
      - refreshExpiryTime
      - accessExpiryTimeStamp
      - refreshExpiryTimeStamp
    Token2:
      type: object
      properties:
        accessExpiryTime:
          type: integer
          example: 3266702264075865762
          format: int64
        accessExpiryTimeStamp:
          type: string
          example: Ipsum ex dolores unde nemo itaque.
        accessToken:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
        refreshExpiryTime:
          type: integer
          example: 7183912702272291221
          format: int64
        refreshExpiryTimeStamp:
          type: string
          example: Dolores accusantium eum recusandae maiores qui dolore.
        refreshToken:
          type: string
          example: Odio est velit vel.
        token:
          type: string
          example: Est porro.
      example:
        accessExpiryTime: 5196807279474169960
        accessExpiryTimeStamp: Optio omnis doloribus minima officiis aut aut.
        accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
        refreshExpiryTime: 8764384405603082437
        refreshExpiryTimeStamp: A consequatur eos nisi.
        refreshToken: At vero.
        token: Odio itaque aut.
      required:
      - accessToken
      - refreshToken
      - accessExpiryTime
      - refreshExpiryTime
      - accessExpiryTimeStamp
      - refreshExpiryTimeStamp
tags:
- name: auth
  description: RESTFUL API Backend for Invoicify. An open source invoicing web app.
- name: cms
  description: CMS service for SpaceCMS. An open source content management system.
