swagger: "2.0"
info:
  title: Invoice App API Service
  description: RESTFUL API Backend for Invoicify. An open source invoicing web app.
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /create-account:
    post:
      tags:
      - invoice
      summary: create-account invoice
      operationId: invoice#create-account
      parameters:
      - name: Create-AccountRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/InvoiceCreateAccountRequestBody'
          required:
          - email
          - name
          - password
      responses:
        "201":
          description: Created response.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/InvoiceCreateAccountBadrequestResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/InvoiceCreateAccountUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/InvoiceCreateAccountNotfoundResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/InvoiceCreateAccountServererrorResponseBody'
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - invoice
      summary: Download ./gen/http/openapi.json
      operationId: invoice#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  InvoiceCreateAccountBadrequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create-account_badrequest_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceCreateAccountNotfoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: create-account_notfound_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceCreateAccountRequestBody:
    title: InvoiceCreateAccountRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email address of the user
        example: Ut hic et quaerat quasi.
      id:
        type: string
        description: ID of the user
        example: Voluptas libero et quas nulla.
      name:
        type: string
        description: Full name of the user
        example: Nam est fugiat qui.
      password:
        type: string
        description: Password of the user. This is never returned to the client.
        example: Et dolore nihil laborum facilis libero perferendis.
    example:
      email: Fuga voluptas et ab sed.
      id: Quis quia rerum autem est culpa.
      name: Earum voluptatem architecto ea et.
      password: Corrupti ad nam velit architecto illum.
    required:
    - email
    - name
    - password
  InvoiceCreateAccountServererrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create-account_servererror_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceCreateAccountUnauthorizedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: create-account_unauthorized_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
